export const cities = [
    { label: 'Rio Branco - AC' },
    { label: 'Maceió - AL' },
    { label: 'Manaus - AM' },
    { label: 'Camaçari - BA' },
    { label: 'Catu - BA' },
    { label: 'Feira de Santana - BA' },
    { label: 'Lauro de Freitas - BA' },
    { label: 'Luis Eduardo Magalhães - BA' },
    { label: 'Salvador - BA' },
    { label: 'Vitória da Conquista - BA' },
    { label: 'Fortaleza - CE' },
    { label: 'Brasilia - DF' },
    { label: 'Cachoeiro de Itapemirim - ES' },
    { label: 'Guarapari - ES' },
    { label: 'Serra - ES' },
    { label: 'Vila Velha - ES' },
    { label: 'Vitória - ES' },
    { label: 'Anápolis - GO' },
    { label: 'Aparecida de Goiânia - GO' },
    { label: 'Caldas Novas - GO' },
    { label: 'Goiânia - GO' },
    { label: 'São Patrício - GO' },
    { label: 'Trindade - GO' },
    { label: 'São Luis - MA' },
    { label: 'Araguari - MG' },
    { label: 'Belo Horizonte - MG' },
    { label: 'Betim - MG' },
    { label: 'Contagem - MG' },
    { label: 'Coronel Fabriciano - MG' },
    { label: 'Divinópolis - MG' },
    { label: 'Formiga - MG' },
    { label: 'Itajubá - MG' },
    { label: 'Itauna - MG' },
    { label: 'Itatiaiaçu - MG' },
    { label: 'Juiz de Fora - MG' },
    { label: 'Lavras - MG' },
    { label: 'Monte Carmelo - MG' },
    { label: 'Montes Claros - MG' },
    { label: 'Nova Lima - MG' },
    { label: 'Nova Serrana - MG' },
    { label: 'Para de Minas - MG' },
    { label: 'Pedro Leopoldo - MG' },
    { label: 'Pouso Alegre - MG' },
    { label: 'Santa Rita do Sapucai - MG' },
    { label: 'Sao José da Lapa - MG' },
    { label: 'Teofilo Otoni - MG' },
    { label: 'Uberaba - MG' },
    { label: 'Uberlandia - MG' },
    { label: 'Campo Grande - MS' },
    { label: 'Dourados - MS' },
    { label: 'Cuiabá - MT' },
    { label: 'Primavera do Leste - MT' },
    { label: 'Rondonópolis - MT' },
    { label: 'Tangará da Serra - MT' },
    { label: 'Várzea Grande - MT' },
    { label: 'Ananindeua - PA' },
    { label: 'Belem - PA' },
    { label: 'Campina Grande - PB' },
    { label: 'João Pessoa - PB' },
    { label: 'Camaragibe - PE' },
    { label: 'Caruaru - PE' },
    { label: 'Jaboatão dos Guararapes - PE' },
    { label: 'Olinda - PE' },
    { label: 'Recife - PE' },
    { label: 'Teresina - PI' },
    { label: 'Almirante Tamandaré - PR' },
    { label: 'Apucarana - PR' },
    { label: 'Arapongas - PR' },
    { label: 'Campo Largo - PR' },
    { label: 'Campo Mourão - PR' },
    { label: 'Cascavel - PR' },
    { label: 'Castro - PR' },
    { label: 'Cianorte - PR' },
    { label: 'Colombo - PR' },
    { label: 'Cornélio Procópio - PR' },
    { label: 'Curitiba - PR' },
    { label: 'Fazenda Rio Grande - PR' },
    { label: 'Foz do Iguaçú - PR' },
    { label: 'Guarapuava - PR' },
    { label: 'Londrina - PR' },
    { label: 'Marechal Cândido Rondon - PR' },
    { label: 'Maringa - PR' },
    { label: 'Medianeira - PR' },
    { label: 'Paranaguá - PR' },
    { label: 'Paranavaí - PR' },
    { label: 'Pato Branco - PR' },
    { label: 'Pinhais - PR' },
    { label: 'Ponta Grossa - PR' },
    { label: 'Rolandia - PR' },
    { label: 'São José dos Pinhais - PR' },
    { label: 'Umuarama - PR' },
    { label: 'União da Vitoria - PR' },
    { label: 'Angra Dos Reis - RJ' },
    { label: 'Barra Mansa - RJ' },
    { label: 'Campos Dos Goytacazes - RJ' },
    { label: 'Duque de Caxias - RJ' },
    { label: 'Itaboraí - RJ' },
    { label: 'Itaguaí - RJ' },
    { label: 'Itatiaia - RJ' },
    { label: 'Macaé - RJ' },
    { label: 'Niterói - RJ' },
    { label: 'Nova Iguaçu - RJ' },
    { label: 'Queimados - RJ' },
    { label: 'Resende - RJ' },
    { label: 'Rio Bonito - RJ' },
    { label: 'Rio das Ostras - RJ' },
    { label: 'Rio de Janeiro - RJ' },
    { label: 'São João do Meriti - RJ' },
    { label: 'Teresópolis - RJ' },
    { label: 'Volta Redonda - RJ' },
    { label: 'Natal - RN' },
    { label: 'Bento Gonçalves - RS' },
    { label: 'Cachoeirinha - RS' },
    { label: 'Campo Bom - RS' },
    { label: 'Canoas - RS' },
    { label: 'Caxias do Sul - RS' },
    { label: 'Erechim - RS' },
    { label: 'Esteio - RS' },
    { label: 'Farroupilha - RS' },
    { label: 'Gramado - RS' },
    { label: 'Gravataí - RS' },
    { label: 'Guaíba  - RS' },
    { label: 'Ijuí - RS' },
    { label: 'Lajeado - RS' },
    { label: 'Montenegro - RS' },
    { label: 'Novo Hamburgo - RS' },
    { label: 'Panambi - RS' },
    { label: 'Passo Fundo - RS' },
    { label: 'Pelotas - RS' },
    { label: 'Porto Alegre - RS' },
    { label: 'Rio Grande - RS' },
    { label: 'Santa Cruz do Sul - RS' },
    { label: 'Santa Maria - RS' },
    { label: 'Santa Rosa - RS' },
    { label: 'São Leopoldo - RS' },
    { label: 'Sapucaia do Sul - RS' },
    { label: 'Sobradinho - RS' },
    { label: 'Taquara - RS' },
    { label: 'Cacoal - RO' },
    { label: 'Araquari - SC' },
    { label: 'Balneário Camboriú - SC' },
    { label: 'Balneário Piçarras - SC' },
    { label: 'Barra Velha - SC' },
    { label: 'Biguaçu - SC' },
    { label: 'Blumenau - SC' },
    { label: 'Braço Do Norte - SC' },
    { label: 'Brusque - SC' },
    { label: 'Canoinhas - SC' },
    { label: 'Chapecó - SC' },
    { label: 'Cocal do Sul - SC' },
    { label: 'Concórdia - SC' },
    { label: 'Criciúma - SC' },
    { label: 'Curitibanos - SC' },
    { label: 'Florianópolis - SC' },
    { label: 'Garopaba - SC' },
    { label: 'Garuva - SC' },
    { label: 'Gaspar - SC' },
    { label: 'Guaramirim - SC' },
    { label: 'Ibirama - SC' },
    { label: 'Içara - SC' },
    { label: 'Imbituba - SC' },
    { label: 'Indaial - SC' },
    { label: 'Itajaí - SC' },
    { label: 'Jaraguá do Sul - SC' },
    { label: 'Joaçaba - SC' },
    { label: 'Joinville - SC' },
    { label: 'Lages - SC' },
    { label: 'Luarentino - SC' },
    { label: 'Mafra - SC' },
    { label: 'Massaranduba - SC' },
    { label: 'Mondaí - SC' },
    { label: 'Morro da Fumaça - SC' },
    { label: 'Navegantes - SC' },
    { label: 'Nova Veneza - SC' },
    { label: 'Palhoça - SC' },
    { label: 'Palmitos - SC' },
    { label: 'Penha - SC' },
    { label: 'Pinhalzinho - SC' },
    { label: 'Pomerode - SC' },
    { label: 'Porto União - SC' },
    { label: 'Pouso Redondo - SC' },
    { label: 'Rio do Campo - SC' },
    { label: 'Rio do Sul - SC' },
    { label: 'Rio Negrinho - SC' },
    { label: 'São Bento do Sul - SC' },
    { label: 'São Francisco Do Sul - SC' },
    { label: 'São José - SC' },
    { label: 'São Miguel do Oeste - SC' },
    { label: 'Schroeder - SC' },
    { label: 'Sombrio - SC' },
    { label: 'Taió - SC' },
    { label: 'Tangará - SC' },
    { label: 'Tijucas - SC' },
    { label: 'Timbó - SC' },
    { label: 'Treze Tílias - SC' },
    { label: 'Videira - SC' },
    { label: 'Xanxerê - SC' },
    { label: 'Americana - SP' },
    { label: 'Andradina - SP' },
    { label: 'Araraquara - SP' },
    { label: 'Araras - SP' },
    { label: 'Arujá - SP' },
    { label: 'Atibaia - SP' },
    { label: 'Barueri - SP' },
    { label: 'Bauru - SP' },
    { label: 'Bertioga - SP' },
    { label: 'Boituva - SP' },
    { label: 'Birigui - SP' },
    { label: 'Bragança Paulista - SP' },
    { label: 'Campinas - SP' },
    { label: 'Capivari - SP' },
    { label: 'Carapicuíba - SP' },
    { label: 'Catanduva - SP' },
    { label: 'Cerquilho - SP' },
    { label: 'Cotia - SP' },
    { label: 'Diadema - SP' },
    { label: 'Embu Das Artes - SP' },
    { label: 'Franca - SP' },
    { label: 'Guararema - SP' },
    { label: 'Guarujá - SP' },
    { label: 'Guarulhos - SP' },
    { label: 'Itapevi - SP' },
    { label: 'Itu - SP' },
    { label: 'Jaboticabal - SP' },
    { label: 'Jardinópolis - SP' },
    { label: 'Jacareí - SP' },
    { label: 'Jambeiro - SP' },
    { label: 'Jundiaí - SP' },
    { label: 'Marília - SP' },
    { label: 'Matão - SP' },
    { label: 'Mauá - SP' },
    { label: 'Mirandópolis - SP' },
    { label: 'Mirassol - SP' },
    { label: 'Mogi Das Cruzes - SP' },
    { label: 'Olímpia - SP' },
    { label: 'Osasco - SP' },
    { label: 'Ourinhos - SP' },
    { label: 'Paulínia - SP' },
    { label: 'Piedade - SP' },
    { label: 'Piracicaba - SP' },
    { label: 'Praia Grande - SP' },
    { label: 'Presidente Prudente - SP' },
    { label: 'Registro - SP' },
    { label: 'Ribeirão Pires - SP' },
    { label: 'Ribeirão Preto - SP' },
    { label: 'Rio Claro - SP' },
    { label: 'Salto - SP' },
    { label: 'Santa Bárbara d\'Oeste - SP' },
    { label: 'Santana De Parnaíba - SP' },
    { label: 'Santo André - SP' },
    { label: 'Santos - SP' },
    { label: 'São Bernardo do Campo - SP' },
    { label: 'São Caetano do Sul - SP' },
    { label: 'São Carlos - SP' },
    { label: 'São João da Boa Vista - SP' },
    { label: 'São José do Rio Preto - SP' },
    { label: 'São José dos Campos - SP' },
    { label: 'São Paulo - SP' },
    { label: 'São Pedro - SP' },
    { label: 'São Vicente - SP' },
    { label: 'Sertãozinho - SP' },
    { label: 'Sorocaba - SP' },
    { label: 'Suzano - SP' },
    { label: 'Tatui - SP' },
    { label: 'Ubatuba - SP' },
    { label: 'Vargem Grande Paulista - SP' },
    { label: 'Vinhedo - SP' },
    { label: 'Votuporanga - SP' },
    { label: 'Aracaju - SE' },
    { label: 'Araguaína - TO' },
    { label: 'Palmas - TO' }
];